/**
 * Deterministic project-docs retrieval: cosine search over
 * data/docs_index.json (generated by scripts/embed_docs.ts), with the pure
 * hash encoding in lib/embed.ts. No network, no LLM, no dependencies.
 */

import docsIndexJson from "../data/docs_index.json";
import { DIMS, ENCODER, embed } from "./embed";

export { DIMS, ENCODER, embed };

export type DocsChunk = {
  id: string;
  source: string;
  heading: string;
  text: string;
  embedding: number[];
};

export type DocsIndex = {
  encoder: "hash-v1";
  dims: 256;
  chunks: DocsChunk[];
};

const docsIndex = docsIndexJson as DocsIndex;

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  for (let i = 0; i < DIMS; i += 1) dot += a[i] * b[i];
  return dot;
}

function normaliseLimit(limit: number): number {
  const requested = Number.isFinite(limit) ? Math.trunc(limit) : 5;
  return Math.min(Math.max(requested, 1), 10);
}

/** Top docs passages for a query, highest cosine similarity first. */
export function retrieveDocs(
  query: string,
  limit = 5,
): { source: string; heading: string; score: number; text: string }[] {
  if (typeof query !== "string" || !query.trim()) return [];
  const vector = embed(query);
  return docsIndex.chunks
    .map((chunk) => ({
      source: chunk.source,
      heading: chunk.heading,
      score: cosine(vector, chunk.embedding),
      text: chunk.text,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, normaliseLimit(limit));
}
